export const VAT_RATES = {
	UK_STANDARD: 0.2,
	IE_REDUCED: 0.135,
	IE_STANDARD: 0.23,
	EXEMPT: 0,
} as const;

export const BUSINESS_RULES = {
	EFFICIENCY_CAP: 0.75,
	SLIPPAGE_FACTOR: 1.15,
	EMPLOYER_BURDEN: 1.3,
	CORP_TAX_BUFFER: 0.8,
	MAX_DIRECT_COST_PCT: 0.8,
	WEEKS_PER_MONTH: 4.33,
	WIN_RATE: 0.3,
	LEAD_CONVERSION_RATE: 0.3,
} as const;
